"""Standalone validation oracle for bank-aware 3D-DRAM operator modeling.

This package intentionally has no hooks into Mosaic's default coarse path.
It is an opt-in source of constructive layout/swizzle witnesses, strict bank
lower bounds, and reproducible validation artifacts.
"""

from .spec import DramBankSpec
from .layout import BankSwizzle, MatrixAccess, TensorLayout
from .l2_cache import (
    DeterministicFifoCache,
    FifoAccessResult,
    GemmL2Result,
    L2CacheSpec,
    L2OperandStats,
)
from .parallel import ParallelBackend
from .engine import (
    BankHistogram,
    BankServiceResult,
    build_bank_histogram,
    fixed_job_parallel_lower_bound_cycles,
    service_request_groups,
    service_requests,
    service_sectors,
    sector_parallel_lower_bound_cycles,
)
from .gemm import (
    GemmBankOptions,
    GemmBankResult,
    GemmLayoutSet,
    GemmLayoutSearchResult,
    GemmProblem,
    GemmTiling,
    default_layout_candidates,
    make_layout_set,
    model_gemm_bank,
    search_gemm_layouts,
)
from .pipeline import (
    BankAwareGemmPipelineResult,
    PipelineSearchResult,
    model_gemm_pipeline,
    pipeline_cycles,
    search_layouts_and_stages,
)
from .multi_cluster import (
    CannonClusterRound,
    CannonPlan,
    CannonResult,
    CannonRoundResult,
    ClusterGrid,
    ClusterUnitSpec,
    DistributedGemmPlan,
    DistributedGemmResult,
    DistributedL2EpochResult,
    DistributedL2Session,
    DistributedL2Stats,
    ExtentSlice,
    LineAccessOutcome,
    LineAccessSource,
    LineRequestEvent,
    LocalModelConfig,
    MemoryReadStageResult,
    MemoryWriteStageResult,
    NoCResult,
    NoCSpec,
    OwnerBankAccessResult,
    PhysicalLineId,
    PlacementKind,
    TensorPlacement,
    TensorReadRequest,
    TensorWriteRequest,
    TrafficFlow,
    model_cannon_gemm,
    model_distributed_gemm,
    model_read_stage,
    model_write_stage,
    split_extent,
)

__all__ = [
    "BankHistogram",
    "BankServiceResult",
    "BankSwizzle",
    "BankAwareGemmPipelineResult",
    "DramBankSpec",
    "DeterministicFifoCache",
    "FifoAccessResult",
    "MatrixAccess",
    "GemmBankOptions",
    "GemmBankResult",
    "GemmLayoutSet",
    "GemmLayoutSearchResult",
    "GemmL2Result",
    "GemmProblem",
    "GemmTiling",
    "PipelineSearchResult",
    "ParallelBackend",
    "L2CacheSpec",
    "L2OperandStats",
    "TensorLayout",
    "CannonClusterRound",
    "CannonPlan",
    "CannonResult",
    "CannonRoundResult",
    "ClusterGrid",
    "ClusterUnitSpec",
    "DistributedGemmPlan",
    "DistributedGemmResult",
    "DistributedL2EpochResult",
    "DistributedL2Session",
    "DistributedL2Stats",
    "ExtentSlice",
    "LineAccessOutcome",
    "LineAccessSource",
    "LineRequestEvent",
    "LocalModelConfig",
    "MemoryReadStageResult",
    "MemoryWriteStageResult",
    "NoCResult",
    "NoCSpec",
    "OwnerBankAccessResult",
    "PhysicalLineId",
    "PlacementKind",
    "TensorPlacement",
    "TensorReadRequest",
    "TensorWriteRequest",
    "TrafficFlow",
    "build_bank_histogram",
    "fixed_job_parallel_lower_bound_cycles",
    "service_request_groups",
    "service_requests",
    "service_sectors",
    "sector_parallel_lower_bound_cycles",
    "default_layout_candidates",
    "make_layout_set",
    "model_gemm_bank",
    "model_gemm_pipeline",
    "model_cannon_gemm",
    "model_distributed_gemm",
    "model_read_stage",
    "model_write_stage",
    "pipeline_cycles",
    "search_gemm_layouts",
    "search_layouts_and_stages",
    "split_extent",
]
